### ISSUE TITLE
Nav Sat Map crashes

### ISSUE THREAD

**Issue by JaouadROS** [gazebosim/gz-sim#1919] opened 2023-03-07 16:25 UTC
## Environment
* OS Version:  Ubuntu 22.04 
* Source build - Fortress
  
  
* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section. 
    - Rendering plugin: ogre2. 
      - [X] Sensor rendering error. 
      - [X] GUI rendering error. 
    - Generally, mention all circumstances that might affect rendering capabilities: 
      - [X] running on a signle GPU machine with RTX 3060 LHR (discrete GPU without integrated GPU)
      - [X] running on real hardware
      - [X] GPU is concurrently used for other tasks
        - [X] desktop acceleration
        - [X] video decoding (i.e. a playing Youtube video)

## Steps to reproduce

1. ruby $(which ign) gazeb
2. Search for Nav Sat Map and click on the corresponding entity
3. CPU runs at 100% (single thread)

## Description
* Expected behavior: 

When adding the Nav Sat Map entity, I expect a side panel with a map and GPS coordinates, just like in [this](https://github.com/gazebosim/ros_gz/tree/humble/ros_gz_sim_demos#gnss) tutorial.

* Actual behavior: 

Once I click on Nav Sat Map, my CPU (one thread) runs at 100% indefinitely until ubuntu asks me to wait or Force Quit.

## Output

```
[GUI] [Dbg] [Application.cc:426] Loading plugin [NavSatMap]
[GUI] [Wrn] [Application.cc:797] [QT] file::/NavSatMap/NavSatMap.qml:160:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[GUI] [Wrn] [Application.cc:797] [QT] QObject::connect(QQuickWindow, QDeclarativeGeoMap): invalid nullptr parameter
[GUI] [Msg] Added plugin [Navigation satellite map] to main window
[GUI] [Msg] Loaded plugin [NavSatMap] from path [/home/dell/Documents/gazebo_fortress/install/lib/ign-gui-6/plugins/libNavSatMap.so]
[GUI] [Wrn] [Application.cc:797] [QT] QGeoTileProviderOsm: Tileserver disabled at  QUrl("http://maps-redirect.qt.io/osm/5.8/satellite")
[GUI] [Wrn] [Application.cc:797] [QT] QGeoTileFetcherOsm: all providers resolved
```

![Screenshot from 2023-03-07 17-19-42](https://user-images.githubusercontent.com/8393796/223483532-e0f8b483-a5c3-4fdf-af89-3b6ba4c231d4.png)

**Comment by JaouadROS** [comment] 2023-03-07 16:50
@caguero Thank you, it seems that it is the same issue and it hasn't been solved.

**Comment by azeey** [comment] 2023-03-07 20:31
Duplicate of https://github.com/gazebosim/gz-gui/issues/482

**Closed by azeey** 2023-03-07 20:31 UTC
Labels: bug
